name: Run PyTest

on:
  push:
    branches:
      - "fixation-detection-3"  # Runs tests when pushing to main
  pull_request:
    branches:
      - main  # Runs tests on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the runner environment
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your repository
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Use the Python version for your project

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flaskr/fixation/requirements.txt

      - name: Run PyTest
        run: python -m pytest ./tests/.  # Run all tests
        working-directory: flaskr/fixation
